theme: jekyll-theme-primer
title: Stephen Ambrose Beck - National Medal
tagline: American missionary, Korean independence advocate
description: >-
  The Korean Order of Merit for National Foundation awarded to the American
  missionary Stephen Ambrose Beck in 2015, and the 2026 search for his
  descendants.
